# Basic workflow for running ARM template test toolkit on PR

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  armtest:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2

    - name: Run ARM TTK tests
      working-directory: scripts
      run: .\VerifyTemplates.ps1
