name: Generate Bicep Changelog
on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: generate bicep changelog
        run:  |
          pwd
          ./scripts/bicep_changelog.sh
        shell: bash

      - name: show changes
        run: |
          git status

      - name: Commit updated CHANGELOG
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: ${{ github.event.pull_request.head.ref }}
          commit_message: Update BICEP CHANGELOG
          file_pattern: BICEP_CHANGELOG.md